version: "3.8"
services:
  spark-master:
    build:
      context: ./docker
      dockerfile: Dockerfile.base
    command: start-master.sh
    ports:
      - "7077:7077"
      - "8080:8080"
  spark-worker:
    build:
      context: ./docker
      dockerfile: Dockerfile.base
    command: start-worker.sh spark://spark-master:7077
    depends_on:
      - spark-master
  notebook:
    image: jupyter/pyspark-notebook
    volumes:
      - ./src:/home/jovyan/src
      - ./notebooks:/home/jovyan/notebooks
    ports:
      - "8888:8888"
