version: "3.9"

services:
  jupyter-pyspark:
    build:
      context: ..
      dockerfile: docker/Dockerfile.base
    container_name: jupyter-pyspark
    ports:
      - "8888:8888"
    volumes:
      - ..:/app
    environment:
      - PYSPARK_PYTHON=/usr/local/bin/python
      - PYSPARK_DRIVER_PYTHON=/usr/local/bin/python
      - JUPYTER_TOKEN=changeme

    networks:
      - spark-network
      - minio-net
    restart: unless-stopped

  minio:
    image: minio/minio:latest # corregido “lastest” → “latest”
    ports:
      - "9000:9000" # acceso S3 API
      - "9001:9001" # consola web de MinIO (opcional pero muy útil)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - minio-net

volumes:
  minio_data:

networks:
  minio-net:
  spark-network:
    driver: bridge
